source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails'
gem 'haml', '~> 4.0.6'
gem 'foundation-rails'
gem 'bcrypt-ruby'
gem 'will_paginate'
gem 'will_paginate-foundation'
gem 'mail', '~> 2.6.3'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder'
# gem 'activemerchant'
gem 'active_utils'
gem 'active_shipping'
gem 'roadie-rails', '~> 1.0.4'
gem 'carmen-rails'
gem 'roo', '~> 2.7.1'
gem 'stripe', '~> 2.1.0'
gem 'figaro', '~> 1.1.1'
gem 'capistrano', '~> 3.5.0'
gem 'capistrano-bundler', '~> 1.1.4'
gem 'capistrano-rails', '~> 1.1.6'
gem 'capistrano-rbenv', '~> 2.0.4', require: false

group :development, :test do
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
  gem 'letter_opener'
  gem 'byebug'
  gem 'pry'
end

group :test do
  gem 'vcr'
  gem 'webmock'
  gem 'faker'
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'simplecov', require: false
end