source 'https://rubygems.org'
ruby '2.4.1'

gem 'rails'
gem 'haml', '~> 4.0.6'
gem 'foundation-rails', '~> 5.5.3.2'
gem 'bcrypt'
gem 'will_paginate'
gem 'will_paginate-foundation'
gem 'mail'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'active_shipping'
gem 'active_utils'
gem 'roadie-rails'
gem 'carmen-rails', :git => 'https://github.com/SCA2/carmen-rails'
gem 'roo', '~> 2.7.1'
gem 'stripe', '~> 2.1.0'
gem 'figaro', '~> 1.1.1'
gem 'capistrano', '~> 3.8.0'
gem 'capistrano-bundler', '~> 1.2.0'
gem 'capistrano-rails', '~> 1.2.3'
gem 'capistrano-rbenv', '~> 2.1.1', require: false

group :development, :test do
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
  gem 'letter_opener'
  gem 'byebug'
end

group :test do
  gem 'vcr'
  gem 'webmock'
  gem 'faker'
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'simplecov', require: false
end