development:
  adapter: postgresql
  encoding: unicode
  database: sca_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: sca_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sca_production
  pool: 5
